import type { AdType } from "$lib/types/ad";

export const ads: AdType[] = [
  {
    banners: ["/ads/ad1.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "", href: "" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad2.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Learn more", href: "https://osbrainfoundation.org" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad3.webp"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "", href: "" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    inters: ["/ads/ad4.webp"],
    format: "INTERSTITIAL",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "", href: "" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad5.webp"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Call us", href: "tel:+233544929791" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad6.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Get app", href: "https://martlify.com/" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad7.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Call us", href: "tel:+233202262143" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad8.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Get one", href: "tel:+233249632272" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad9.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Download", href: "https://martlify.com/" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad10.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "", href: "" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad11.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Call us", href: "tel:+233202262143" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad12.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "", href: "" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad13.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Donate", href: "https://selar.co/7sz5" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad14.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Learn more", href: "https://osbrainfoundation.org" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad15.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Call us", href: "tel:+233242366444" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },

  {
    banners: ["/ads/ad16.jpg"],
    format: "BANNER",
    id: "",
    customerId: "",
    budget: 0,
    views: 0,
    impressions: 0,
    status: "RUNNING",
    referral: { text: "Call us", href: "tel:+233242366444" },
    reach: { stretch: "NATIONWIDE", region: "", city: "" },
    message: "",
  },
];
