export const readTopics = [
  "Poetry",
  "Culture",
  "Devotional",
  "Pan Africanism",
  "Politics & Policy",
  "Tech",
  "Business & Industrial",
  "Money & Finance",
  "Food & Drinks",
  "Film & TV",
  "Books",
  "Lifestyle & Entertainment",
  "Travel & Tourism",
  "Sports",
  "Faith and Spirituality",
  "News",
  "Music",
  "Comic",
  "Art & Illustration",
  "Climate",
  "Science",
  "Health, Wellness & Fitness",
  "Literature",
  "Fiction",
  "Relationships & Parenting",
  "Travel & Tourism",
  "Education",
  "Philosophy",
  "History",
  "Humor & Jokes",
  "Fashion & Beauty",
  "Mindfulness",
  "Career & Jobs",
  "Public safety",
];
